TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../rtl/axi_lite_reg_interface.sv
TOPLEVEL = axi_lite_reg_interface
MODULE = cocotb_axi_lite_reg_interface

SIM = icarus
#EXTRA_ARGS += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim